backend:
  name: github
  repo: LuisMMVieira/luis-portfolio
  branch: main
local_backend: true

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: hero
    label: "Hero"
    files:
      - file: "src/content/hero.md"
        label: "Hero Section"
        name: "hero"
        fields:
          - { name: title, label: "Title", widget: "string" }
          - { name: subtitle, label: "Subtitle", widget: "string" }
          - { name: body, label: "Body", widget: "markdown" }
  - name: about
    label: "About"
    files:
      - file: "src/content/about.md"
        label: "About Section"
        name: "about"
        fields:
          - { name: title, label: "Title", widget: "string" }
          - { name: body, label: "Body", widget: "markdown" }
  - name: work
    label: "Selected Work"
    files:
      - file: "src/content/work.json"
        label: "Work"
        name: "work"
        format: "json"
        fields:
          - { name: work, label: "Work Items", widget: "list", fields: [ { name: title, label: "Title", widget: "string" }, { name: description, label: "Description", widget: "string" }, { name: link, label: "Link", widget: "string" }, { name: image, label: "Image", widget: "image" } ] }
  - name: current
    label: "Currently"
    files:
      - file: "src/content/current.md"
        label: "Currently Section"
        name: "current"
        fields:
          - { name: title, label: "Title", widget: "string" }
          - { name: body, label: "Body", widget: "markdown" }
  - name: background
    label: "Background"
    files:
      - file: "src/content/background.md"
        label: "Background Section"
        name: "background"
        fields:
          - { name: title, label: "Title", widget: "string" }
          - { name: body, label: "Body", widget: "markdown" }
  - name: contact
    label: "Contact"
    files:
      - file: "src/content/contact.md"
        label: "Contact Section"
        name: "contact"
        fields:
          - { name: title, label: "Title", widget: "string" }
          - { name: email, label: "Email", widget: "string" }
          - { name: body, label: "Body", widget: "markdown" }